learning_django/blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"

urlpatterns = [
    path('', blog, name='blog'),
    path('profile', profile, name='profile'),
    path('ajax_more', ajax_more, name='ajax_more'),
    path('add_article', add_article, name='add_article'),
    path('article_details/<int:pk>', article_details, name='article_details'),
]

learning_django/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('comment/', include('comment.urls')),

]



from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    

learning_django/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.utils.html import format_html
from django.core.validators import MinLengthValidator, MaxLengthValidator, RegexValidator
from django.core.exceptions import ValidationError

from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from django.urls import reverse

# Create your models here.
class Article(models.Model):
    CONDITION_CHOICE = (
        ('p', 'published'),
        ('d', 'draft'),
        ('r', 'rejected')
    )

    title = models.CharField(max_length=200)
    content = models.TextField()

    id_number = models.CharField(
        max_length=11,
        blank=True,
        validators=[
            MinLengthValidator(10),
            MaxLengthValidator(11),
            RegexValidator(
                regex=r'^[0-9]*$',
                message='نام کاربری فقط شامل عدد می تواند باشد',
                code='nomatch',
            )
        ],
        verbose_name='شماره‌ملی/شناسه‌ملی',
    )

    thumbnail =  models.ImageField(upload_to='article_image', blank=True)

    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)

    condition = models.CharField(max_length=1, choices=CONDITION_CHOICE, blank=True, default='d')

    slug = models.SlugField(max_length =200, unique=True, blank=True, null=True)

    status = models.BooleanField(default=True)

    publish_date = models.DateTimeField(auto_now_add=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    comments = GenericRelation(Comment)

    def get_pic(self):
        a = '<img width=80 src='+self.thumbnail.url+'>'
        return format_html(a)
    
    def mstatus(self):
        if self.status == True:
            a = "<img src='/static/admin/img/icon-yes.svg' alt='True'>"
        else:
            a = "<img src='/static/admin/img/icon-no.svg' alt='False'>"
        return format_html(a)
    
    def __str__(self):
        return str(self.title)
    
    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})

learning_django/blog/forms.py
from django import forms
from .models import *


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = '__all__'
        fields = [
            'title',
            'id_number',
            'content',
            'thumbnail',

        ]

learning_django/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound
from django.contrib.auth import get_user_model
from .models import Article
from .forms import ArticleForm

# Create your views here.
def blog(request):
    user = request.user
    # articles = Article.objects.filter(status=True, condition='p')
    articles = Article.objects.all()
    context={
        'articles':articles,
    }
    return render(request, 'blog/blog.html', context)


def profile(request):
    return HttpResponse("hi")


def add_article(request):
    form = ArticleForm()

    if request.POST:
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save()
            obj.author = request.user
            obj.save()
            return redirect('blog:blog')


    context = {
        'form' : form ,
        
    }
    return render(request, 'blog/add_article.html', context)


def article_details(request, pk):

    try:
        article = Article.objects.get(id=pk)
    except Article.DoesNotExist:
        return HttpResponse("NOT FOUND")


    context = {
        'article':article,
    }
    return render(request, 'blog/article_details.html', context)



def ajax_more(request):
    article_id = request.GET['articleId']
    article = Article.objects.get(id=article_id)
    context = {
        'article':article,
    }
    return render(request, 'blog/ajax_more.html', context)

learning_django/blog/templates/blog/add_article.html
{% load static%}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />

  </head>
  <body>



    <div class="container mt-5">
      <h3 class="mb-2 text-danger">add new article</h3>
        <div class="card">
            <div class="card-body">
              <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}

                <button class="btn btn-success mt-4" type="submit">send</button>
              </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

learning_django/blog/templates/blog/ajax_more.html
<div class="container mt-3">
    <h2>{{article.title}}</h2>
    <p>{{article.author}}</p>
    <div class="card" style="width:400px">
      <img class="card-img-top" src="{{article.thumbnail.url}}" alt="Card image" style="width:100%">
      <div class="card-body">
        <h4 class="card-title">{{article.status}}</h4>
        <p class="card-text">
            {{article.content}}
        </p>
        <a href="{% url 'blog:article_details' article.id %}" class="btn btn-primary">See article</a>
      </div>
    </div>
    <br>    
</div>

learning_django/blog/templates/blog/article_details.html
{% load static%}
{% load ratings %}
{% load comment_tags %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
  </head>
  <body>



    <div class="container mt-5">
      <section class="single-block-wrapper section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="single-post">
                        <div class="post-header mb-5 text-center">
                            <div class="meta-cat">
                                <a href="{% url 'blog:blog'%}" class="btn btn-outline-primary"> back</a>
                            </div>
                            <h2 class="post-title mt-2">
                                {{article.title}}
                            </h2>
                            <div>
                              {% ratings article %}
                            </div>

                            <div class="post-meta">
                                <span class="text-uppercase font-sm letter-spacing-1 mr-3">by {{article.author}}</span>
                                <span class="text-uppercase font-sm letter-spacing-1">{{article.created}}</span>
                            </div>
                            <div class="post-featured-image mt-5">
                                <img src="{{article.thumbnail.url}}" class="img-fluid w-100" alt="featured-image">
                            </div>
                        </div>
                        <div class="post-body">
                            <div class="entry-content">
                                <p>
                                  {{article.content|safe}}
                                </p>
                                
                            </div>
                        </div>

                        <div class="container">
                            <div class="comment">
                                {% render_comments article request %}
                            </div>

                        </div>
                    </div>

                   
                    



                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                    <div class="sidebar sidebar-right">
                        <div class="sidebar-wrap mt-5 mt-lg-0">
                            <div class="sidebar-widget about mb-5 text-center p-3">
                                <div class="about-author">
                                    <img src="images/author.jpg" alt="" class="img-fluid">
                                </div>
                                <h4 class="mb-0 mt-4">{{article.author.first_name}} {{article.author.last_name}}</h4>
                                <p>{{article.author.email}}</p>
                                
                                <img src="images/liammason.png" alt="" class="img-fluid">
                            </div>

                         

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

learning_django/blog/templates/blog/blog.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

  </head>
  <body>



    <div class="container mt-5">
      <a href="{% url 'blog:add_article' %}" class="btn btn-outline-warning mb-5">add article
        <i class="fa fa-plus"></i>
      </a>
        <div class="card" id="para" data-amin="hashemi">
            <div class="card-body">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">title</th>
                        <th scope="col">author</th>
                        <th scope="col">thumbnail</th>
                        <th scope="col">status</th>
                        <th scope="col">condition</th>
                        <th scope="col">publish_date</th>
                        <th scope="col">details</th>
                        <th scope="col">more</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for article in articles %}
                      <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{article.title}}</td>
                        <td>{{article.author.first_name}}-{{article.author.last_name}}</td>
                        {% if article.thumbnail %}
                        <td>{{article.get_pic}}</td>
                        {% else %}
                        <td>no pic</td>
                        {% endif %}
                        <td>{{article.mstatus}}</td>
                        <td>{{article.get_condition_display}}</td>
                        <td>{{article.publish_date}}</td>
                        <td><a href="{% url 'blog:article_details' article.id %}" class="btn btn-outline-primary"><i class='fas fa-eye'></i></a></td>
                        <td><a href="#" class="btn btn-outline-warning more" data-id="{{article.id}}" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class='fas fa-check'></i></a></td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>

            </div>
        </div>
    </div>

        <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="row text-center" id="modal-body">

            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
      $(".more").click(function(){
        var articleId = $(this).data('id')
        var url = "{% url 'blog:ajax_more' %}"
        $.ajax({
        type: "GET",
        url: url,
        data: {
          'articleId':articleId,
          },
        success: function(data) {
          $("#modal-body").html(data)
        },
        });
        // $(".modal-body").html(articleId)
        
      });
    </script>

  </body>
</html>